Added boba's testnet faucets
bobanetwork/boba pull request #261
Opened 2024-10-09 16:16 UTC by katieclay

[:clipboard: Add associated issues, tickets, docs URL here.](https://enyainc.slack.com/archives/C03Q8H79T8V/p1728484471231709?thread_ts=1728484412.295179&cid=C03Q8H79T8V)

## Overview

Added the two Boba testnet faucets to the Boba Faucet docs.

2024-10-09 16:57 UTC, wsdt requested changes

2024-10-09 16:57 UTC, wsdt commented on .gitbook/contents/developer/faucets.md
> +| [Boba BNB Testnet Faucet](https://faucet.testnet.bnb.boba.network/) | Boba Sepolia          |
Boba BNB testnet (network)

2024-10-09 17:02 UTC, wsdt commented on .gitbook/contents/developer/faucets.md
> +| [Boba BNB Testnet Faucet](https://faucet.testnet.bnb.boba.network/) | Boba Sepolia          |
```suggestion
| [Boba BNB Testnet Faucet](https://faucet.testnet.bnb.boba.network/) | Boba BNB Testnet          |
```

2024-10-09 17:03 UTC, wsdt approved these changes
left a suggestion, with that one it should be correct :-)

2024-10-10 16:09 UTC, jyellick approved these changes

2024-10-10 17:08 UTC, merged